# Generated by Django 5.2.8 on 2025-11-19 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_topic_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useradmin',
            options={},
        ),
        migrations.RemoveField(
            model_name='useranggota',
            name='bidang_keahlian',
        ),
        migrations.RemoveField(
            model_name='useranggota',
            name='nidn',
        ),
        migrations.RemoveField(
            model_name='useranggota',
            name='tempat_lahir',
        ),
        migrations.RemoveField(
            model_name='useranggota',
            name='tgl_lahir',
        ),
    ]
