# Generated by Django 5.2.8 on 2025-11-24 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_useradmin_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('nama_perusahaan', models.CharField(max_length=100)),
                ('tanggal_listing', models.DateField(blank=True, null=True)),
                ('current_share', models.PositiveBigIntegerField()),
                ('papan_pencatatan', models.CharField(max_length=50)),
                ('sektor', models.CharField(max_length=100)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('price_change', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('percent_change', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Saham',
                'verbose_name_plural': 'Daftar Saham',
                'ordering': ['symbol'],
            },
        ),
        migrations.CreateModel(
            name='StockUpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10, unique=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='StockData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('open_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('close_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('saham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app.saham')),
            ],
        ),
    ]
