# Generated by Django 5.2.8 on 2025-11-26 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_delete_saham'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saham',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('short_name', models.CharField(blank=True, max_length=255, null=True)),
                ('long_name', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, max_length=10, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('change', models.FloatField(blank=True, null=True)),
                ('change_pct', models.FloatField(blank=True, null=True)),
                ('volume', models.BigIntegerField(blank=True, null=True)),
                ('open_price', models.FloatField(blank=True, null=True)),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('market_cap', models.BigIntegerField(blank=True, null=True)),
                ('pe', models.FloatField(blank=True, null=True)),
                ('forward_pe', models.FloatField(blank=True, null=True)),
                ('pbv', models.FloatField(blank=True, null=True)),
                ('div_yield', models.FloatField(blank=True, null=True)),
                ('div_rate', models.FloatField(blank=True, null=True)),
                ('eps_ttm', models.FloatField(blank=True, null=True)),
                ('eps_forward', models.FloatField(blank=True, null=True)),
                ('eps_year', models.FloatField(blank=True, null=True)),
                ('price_eps_year', models.FloatField(blank=True, null=True)),
                ('shares_outstanding', models.BigIntegerField(blank=True, null=True)),
                ('prev_close', models.FloatField(blank=True, null=True)),
                ('day_high', models.FloatField(blank=True, null=True)),
                ('day_low', models.FloatField(blank=True, null=True)),
                ('avg_vol_3m', models.BigIntegerField(blank=True, null=True)),
                ('avg_vol_10d', models.BigIntegerField(blank=True, null=True)),
                ('week52_high', models.FloatField(blank=True, null=True)),
                ('week52_low', models.FloatField(blank=True, null=True)),
                ('week52_high_change', models.FloatField(blank=True, null=True)),
                ('week52_high_change_pct', models.FloatField(blank=True, null=True)),
                ('week52_low_change', models.FloatField(blank=True, null=True)),
                ('week52_low_change_pct', models.FloatField(blank=True, null=True)),
                ('book_value', models.FloatField(blank=True, null=True)),
                ('confidence', models.CharField(blank=True, max_length=50, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
