# Generated by Django 5.2.8 on 2025-11-26 02:29

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_saham'),
    ]

    operations = [
        migrations.AddField(
            model_name='saham',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=app.models.rename_logo_saham),
        ),
        migrations.AddField(
            model_name='saham',
            name='sektor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
