# Generated by Django 5.2.8 on 2025-11-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_saham_logo_saham_sektor'),
    ]

    operations = [
        migrations.AddField(
            model_name='saham',
            name='papan_pencatatan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
