# Generated by Django 5.2.8 on 2025-11-26 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_saham_papan_pencatatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='saham',
            name='firt_trade_date',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
