# Generated by Django 5.2.8 on 2025-12-13 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_saham_firt_trade_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saham',
            name='firt_trade_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.IntegerField()),
                ('dividend', models.FloatField()),
                ('ex_date', models.DateField(blank=True, null=True)),
                ('pay_date', models.DateField(blank=True, null=True)),
                ('saham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dividends', to='app.saham')),
            ],
        ),
    ]
